### ISSUE TITLE
Convert total time (mins) to time (00h00m)

### ISSUE THREAD

**Issue by jonnymcook1** [flight-club/flight-club#25]
Total time of minutes needs to be changed into hours and minutes of total time

**Comment by sheehanqmd** [comment]
this is the code needed.

changeDuration(minutes) {
        var h = Math.floor(minutes / 60);
        var m = minutes % 60;
        h = h < 10 ? + h : h;
        m = m < 10 ? '0' + m : m;
        return h + 'h' + m + 'm';
      }
