### ISSUE TITLE
too many of the same flight number coming up in data need to figure out how to limit to one flight per flight number.

### ISSUE THREAD

**Issue by sheehanqmd** [flight-club/flight-club#31]

**Comment by jonnymcook1** [comment]
let filteredFlights = []
        let results = response.data.PricedItineraries
        // console.log(results)
        for(let i = 0; i < results.length; i++) {
            let index = filteredFlights.findIndex(obj => obj.AirItinerary.OriginDestinationOptions.OriginDestinationOption[0].FlightSegment[0].FlightNumber === results[i].AirItinerary.OriginDestinationOptions.OriginDestinationOption[0].FlightSegment[0].FlightNumber)
            console.log(index)
            if(index === -1){
                filteredFlights.push(results[i])
            }

        }
        res.send(filteredFlights)

This filter method should be able to give you just one flight by comparing the flight numbers
